services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ../frontend:/www
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx_logs:/var/log/nginx/
      - /ssl:/ssl
    # restart: always
    # command: [nginx-debug, '-g', 'daemon off;'] # 需要 debug 时开启
